sidebar:
  entries:
    - title: Astra automation doc
      url: /index.html
    - section: get-started
    - section: rest-core

homepage:
  tiles:
    - title: Get started
      links:
        - title: Introduction
          summary: Get an overview of the Astra REST API and automation options.
          url: /get-started/introduction.html
