sidebar:
  entries:
    - title: Astra automation doc
      url: /index.html
    - section: intro
    - section: get-started
    - section: rest-core
    - section: object-model
    - section: endpoints
    - section: workflows
    - section: reference
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: Introduction
          summary: Get an overview of the Astra REST API and automation options.
          url: /intro/introduction.html
        - title: Before you begin
          summary: Prepare to get started using the API.
          url: /get-started/before_get_started.html
        - title: Get an API token
          summary: Generate a token you need for API access.
          url: /get-started/get_api_token.html
        - title: Hello world
          summary: Test basic access to the REST API.
          url: /get-started/hello_world.html
    - title: REST implementation
      links:
        - title: Concepts
          summary: Review basics REST concepts.
          url: /rest-core/concepts.html
        - title: HTTP details
          summary: Understand details of the HTTP implementation.
          url: /rest-core/http_details.html
        - title: Security
          summary: Review API security
          url: /rest-core/security.html
        - title: Diagnostics
          summary: Be ready to debug and support the API.
          url: /rest-core/diagnostics_debugging.html
    - title: Object model
      links:
        - title: Introduction to REST endpoints
          summary: Introduction and summary of the REST endpoints.
          url: /object-model/intro_rest_endpoints.html
        - title: Entity-Relationship model
          summary: Internal object nmodel and REST resources.
          url: /object-model/er_model.html
        - title: URL format for API access
          summary: Format of the URL used with the API.
          url: /object-model/url_format.html
        - title: Working with collections
          summary: Advanced techniques for collections.
          url: /object-model/working_with_collections.html
    - title: API endpoints and resources
      links:
        - title: Introduction to REST endpoints
          summary: A high-level introduction to the REST endpoints.
          url: /object-model/intro_rest_endpoints.html
        - title: API endpoints and resources
          summary: Description of all the endpoints as organized into REST APIs.
          url: /endpoints/api_endpoints_resources.html
        - title: User API
          summary: An example of one of the available APIs.
          url: /endpoints/ep_user.html
    - title: Administrative workflows
      links:
        - title: Before you begin
          summary: Prepare to start using the workflows.
          url: /workflows/before_workflow_processes.html
        - title: Identity management
          summary: Workflows used to administer users, credentials, roles, and tokens.
          url: /workflows/admin_wf_identity.html
        - title: Events and notifications
          summary: Workflows used to manage events and notifications.
          url: /workflows/admin_wf_events.html
