---
settings:
  name: Astra Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: Astra Control Automation docs
      url: /index.html
    - section: rn
    - section: intro
    - section: get-started
    - section: rest-core
    - section: additional
    - section: endpoints
    - section: workflows_infra
    - section: workflows
    - section: python
    - section: reference
    - section: information
    - title: Earlier versions
      url: /aa-earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: Introduction
          url: /intro/introduction.html
        - title: Before you begin
          url: /get-started/before_get_started.html
        - title: Get an API token
          url: /get-started/get_api_token.html
        - title: Hello world
          url: /get-started/hello_world.html
    - title: REST implementation
      links:
        - title: REST web services
          url: /rest-core/rest_web_services.html
        - title: HTTP details
          url: /rest-core/http_details.html
        - title: URL format
          url: /rest-core/url_format.html
    - title: Additional considerations
      links:
        - title: RBAC security
          url: /additional/rbac.html
        - title: Working with collections
          url: /additional/working_with_collections.html
        - title: Diagnostics and support
          url: /additional/diagnostics_support.html
        - title: Revoke an API token
          url: /additional/revoke_token.html
    - title: Resources
      links:
        - title: REST resources and collections
          url: /rest-core/resources_collections.html
        - title: Summary of Astra API resources
          url: /endpoints/resources.html
    - title: Workflows
      links:
        - title: Preparation
          url: /get-started/prepare_to_use_workflows.html
        - title: Infrastructure workflows
          url: /workflows_infra/workflows_infra_before.html
        - title: Management workflows
          url: /workflows/workflows_before.html
    - title: Python
      links:
        - title: Before you begin
          url: /python/python_before.html
        - title: List the managed apps
          url: /python/py_list_man_apps.html
