sidebar:
  entries:
    - title: Astra automation doc
      url: /index.html
    - section: intro
    - section: get-started
    - section: rest-core
    - section: additional
    - section: endpoints
    - section: workflows
    - section: reference
    - section: information
    - title: Legal notices
      url: /legal-notices.html

homepage:
  tiles:
    - title: Get started
      links:
        - title: Introduction
          summary: Get an overview of the Astra REST API.
          url: /intro/introduction.html
        - title: Before you begin
          summary: Prepare to get started using the API.
          url: /get-started/before_get_started.html
        - title: Get an API token
          summary: Generate a token you need for API access.
          url: /get-started/get_api_token.html
        - title: Hello world
          summary: Test basic access to the REST API.
          url: /get-started/hello_world.html
    - title: REST implementation
      links:
        - title: REST web services
          summary: Technology foundations of REST web services.
          url: /rest-core/rest_web_services.html
        - title: HTTP details
          summary: Review the details of the HTTP implementation.
          url: /rest-core/http_details.html
    - title: Resources
      links:
        - title: Resources and collections
          summary: Become familiar with the REST resources and collections.
          url: /rest-core/resources_collections.html
        - title: Details of the Astra REST API resources
          summary: Concise introduction to the various resources.
          url: /endpoints/resources.html
        - title: User API
          summary: An example of a typical resource.
          url: /endpoints/ep_user.html
    - title: Administrative workflows
      links:
        - title: Before you begin
          summary: Prepare to start using the workflows.
          url: /workflows/before_workflow_processes.html
        - title: Identity management
          summary: Workflowsto administer users, credentials, roles, and tokens.
          url: /workflows/admin_wf_identity.html
        - title: Events and notifications
          summary: Workflows to manage events and notifications.
          url: /workflows/admin_wf_events.html
