sidebar:
  entries:
    - title: Astra automation doc
      url: /index.html
    - section: intro
    - section: get-started
    - section: rest-core
    - section: object-model
    - section: endpoints
    - section: workflows
    - section: reference

homepage:
  tiles:
    - title: Get started
      links:
        - title: Introduction
          summary: Get an overview of the Astra REST API and automation options.
          url: /intro/introduction.html
        - title: Before you begin
          summary: Prepare to get started using the API.
          url: /get-started/before_get_started.html
    - title: REST implementation
      links:
        - title: Concepts
          summary: Review basics REST concepts.
          url: /rest-core/concepts.html
    - title: Object model
      links:
        - title: Introduction to REST endpoints
          summary: Introduction and summary of the REST endpoints.
          url: /object-model/intro_rest_endpoints.html
        - title: Entity-Relationship model
          summary: Internal object nmodel and REST resources.
          url: /object-model/er_model.html
        - title: URL format for API access
          summary: Format of the URL used with the API.
          url: /object-model/url_format.html
        - title: Working with collections
          summary: Advanced techniques for collections.
          url: /object-model/working_with_collections.html
    - title: Endpoints and resources
      links:
        - title: Core APIs
          summary: Core Astra REST APIs.
          url: /endpoints/epcat_core.html
        - title: Managed application APIs
          summary: REST APIs for managed applications.
          url: /endpoints/epcat_managed_apps.html
        - title: Topology APIs
          summary: Topology REST APIs.
          url: /endpoints/epcat_topology.html
